### ISSUE TITLE
2-2-7-ExploringCategorical.ipynb is inaccessible

### ISSUE THREAD

**Issue by Blend3rman** [tinyMLx/colabs#12]
Google colab shows the following message when trying to open this notebook:

> ### Notebook loading error
> There was an error loading this notebook. Ensure that the file is accessible and try again.
> 
> JSON.parse: unexpected character at line 417 column 4 of the JSON data
> #### Details:
> `JSON.parse: unexpected character at line 417 column 4 of the JSON data`
> `c/<@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210301-060102-RC00_360156368:1376:452`   
> `Ea@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210301-060102-RC00_360156368:19:336`  
> `Ca.prototype.next_@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210301-060102-RC00_360156368:17:503`   
> `Ga/this.next@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210301-060102-RC00_360156368:20:206`  
> `f@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20210301-060102-RC00_360156368:62:101`

**Comment by plancherb1** [comment]
Thank you -- should be corrected now sorry!

**Comment by Blend3rman** [comment]
I am curious: what caused the error? Was it some unsupported character or a corrupted file?

**Comment by plancherb1** [comment]
I had manually updated a comment in a text editor and added an extra comma
outside of the “string” in a list of strings [] breaking the ipynb syntax.
