### ISSUE TITLE
Update 3-3-12-QAT.ipynb to the latest one from tensorflow

### ISSUE THREAD

**Issue by mglsj** [tinyMLx/colabs#29]
The 3-3-12-QAT.ipynb doesn't work due to some changes in the library. The original TensorFlow notebook has some updates that fixes it.

https://colab.research.google.com/github/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/g3doc/guide/quantization/training_example.ipynb

https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/g3doc/guide/quantization/training_example.ipynb

**Comment by Naeemkh** [comment]
Thanks, @MG-LSJ, the colab is updated.
